language: node_js
node_js:
- 13.11.0
-
services:
- mongodb
deploy:
  provider: lambda
  function_name: lambda-test
  region: us-east-1
  role: arn:aws:iam::311674406834:role/sample-app-dev-us-east-1-lambdaRole
  runtime: nodejs12.x
  handler_name: handler
  secret_access_key:
    secure: mwRV7h+hOWGGbzo/XwHVJ/vG4yXdxLeCJ/hlkRGPlSfZ1DJBSL/UK1DRm0lplNKySXZsnUqdGwTSQLH6/KMKs9IPe8BzutVnOxiYELx67nhqebrjDwhvr6FJCnCqixgdv5wm08TbphNUTO85Z3ljjjcRKGJUcxY295zqAjOuX2NRHoO9V8y84cp1ad59KOFjRqALmLM+fAHIr84xIgJAOTrlGmDgEtLyVV4295E8fuCQeEkgDDPLwprCZYHgFGsUd6ds1TtVXTWQQGI/EzEt8GopKqOfJ3ZVC+VIvbY4kaGFAEF3nGPe+mNOeUTO/+XgwLThzSxX6LZUijCzEYUn4Tl7O+6tVTNZHEhYqnYYXn5xfnZVqXuj7QCnazzm+ZoCMahhWIGrhu1bAgcVcZ9vK8wU5SGx4MWJ8vIBMih0urFF0xWfLHTieKNhp1DJ43iaVmUy7M/vN3vlaKib7I1zqci9+2pxfSE72n/YRUFPgszOR7/1LijwOZYASIxMxFnvntffaLgWD9VZtBhY12wpCnBuKGtCq9yPwqaiJAKvYzrGOkQQ5V/sMG6ygedE4hUupZ4CCX0/5j203dmCRVNoqJs+AMaXbjZK5txNHY8+8kdXhhpWDzKauDP547snWRkb2SmOyDTyhDLfxcXEhdjn+EneN90JkMPTedY+npX+DUU=
  access_key_id:
    secure: TYRQNcLn2ydmoNduyA0Jc0qmWgQMVsEQ9eYspvqU1Xo1yf833qB2TiIdUhoiFN8EdZHLBtcEDKnekePMCbi3vOD+sQBreFkCSZ56VcqF/WO3TrszXIUCW+iyxoL+gK1Ph1avxjj9aZjsPuPzbN5Ob2w+1eJpAuYqRmhR07eXA9z/wMDqoNP9Nj8pGwOOFlMqd3j7TPDsvf5EzbRP1/70JfbZ4w7OZoFBnXUZmAYZX+Bz63qnjIJhSkw45Ht/vJYzdKdeNX+SSCPRdPGAAtD8irT88zjdw3kvQM9ipHStF/M3txM76pGmrszGWOxicc9ioE1MxSUVP93WyGWBj3suxf6d9GWVlKjPatbRsiZ27cuV08MtXTMQFUn9AGqBTWk4eLDZ4WROlpAMHoML2hXXu3gOcEsdrzLgfAECatN2ocOgDzrscf7WuFNSSiOXzrE3njDKTL+CJtPU3sCmJMVkc5olusFPK15Th6MjfrB3QyX1B3LraL3fbBGbYT8TkktZz/naWSIVEeHUscOPLZ1cFlNYR2iRcl1GnCV5XxtM8WULdvziuRka/Y2gks4uj9+8FmTSC6vUGzwdtQsbCAgEgBewAd8g1RCVPYDKXMMBdNE9kkMJFMIvixYaqJffwNo3LgKs7Pjrri9fQlM5tx7ejFmdw8OIqmvn09rHKgRsvl8=
